Spree::ProductImport.settings = {
    :column_mappings => { #Change these for manual mapping of product fields to the CSV file
                          :taxonomies => 0,
                          :brands => 2,
                          :name => 3,
                          :available_on => 4,
                          :condition => 5,
                          :size_clothes => 6,
                          :color => 7,
                          :sku => 8,
                          :master_price => 9,
                          :cost_price => 10,
                          :weight => 11,
                          :height => 12,
                          :width => 13,
                          :depth => 14,
                          :Model => 15,
                          :image_main => 16,
                          :image_2 => 17,
                          :image_3 => 18,
                          :image_4 => 19,
                          :image_5 => 20,
                          :variant_main => 21,
                          :variant_2 => 22,
                          :variant_3 => 23,
                          :variant_4 => 24,
                          :variant_5 => 25,
                          :description => 26,
                          :composition => 28,
                          :look => 29,
                          :style => 30,
                          :collection => 31,
                          :on_hand => 32,
                          :slug => 33,
                          :category_sku => 34


    },
    :num_prods_for_delayed => 10, #From this number of products, the process is executed in delayed_job. Under it is processed immediately.
    :create_missing_taxonomies => true,
    :taxonomy_fields => [:taxonomies], #Fields that should automatically be parsed for taxons to associate
    :image_fields_products => [:image_main, :image_2, :image_3, :image_4, :image_5], #Image fields that should be parsed for image locations of products
    :image_fields_variants => [:variant_main, :variant_2, :variant_3, :ivariant_4, :ivariant_5], #Image fields that should be parsed for image locations of variants
    :image_text_products => :name, #Field that contains alt text for images of product.
    :image_text_variants => :name, #Field that contains alt text for images of variant.
    :product_image_path => "", #The location of images on disk
    :rows_to_skip => 1, #If your CSV file will have headers, this field changes how many rows the reader will skip
    :log_to => File.join(Rails.root, '/log/', "import_products_#{Rails.env}.log"), #Where to log to
    :destroy_original_products => false, #Disabled #Delete the products originally in the database after the import?
    :first_row_is_headings => true, #Reads column names from first row if set to true.
    :create_variants => true, #Compares products and creates a variant if that product already exists.
    :price_field => :price, #Field that contains the price of a product. Is required in new products.
    :variant_comparator_field => :slug, #Which product field to detect duplicates on
    :variant_comparator_field_i18n => :slugi18n, #CSV column with translation of variant_comparator_field. Not used yet.
    :multi_domain_importing => false, #If Spree's multi_domain extension is installed, associates products with store.
    :store_field => :store_code, #Which field of the column mappings contains either the store id or store code?
    :transaction => true #import product in a sql transaction so we can rollback when an exception is raised
}